# Generated by Django 4.0.6 on 2022-07-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('currency', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('buy', models.FloatField()),
                ('sell', models.FloatField()),
                ('other', models.FloatField()),
            ],
            options={
                'db_table': 'cotizacion',
                'managed': False,
            },
        ),
    ]
